In [8]:

TEST_DIR = "D:/Depression/images/omkar/"
ME_DIR = "D:/Depression/images/me_original/"

In [9]:
import os

def load_dataset(directory):
    image_paths = []
    labels = []
    
    for label in os.listdir(directory): # label
        for image_name in os.listdir(directory+label): 
            image_path = os.path.join(directory, label, image_name)
            image_paths.append(image_path)
            labels.append(label)
            
        print(label, "Completed")
        
    return image_paths, labels

In [10]:
import pandas as pd

test = pd.DataFrame()
test['image'], test['label'] = load_dataset(TEST_DIR)
test.head()

happy Completed


image  label
0  D:/Depression/images/omkar/happy\1.jpg  happy

In [11]:
import tensorflow as tf
model = tf.keras.models.load_model("D:/Depression/model0.935/model.tf")

In [12]:
from tqdm import tqdm
from keras_preprocessing.image import load_img
import numpy as np

# loads and preprocesses
def extract_features(images):
    features = []
    for image in tqdm(images):
        img = load_img(image, color_mode = "grayscale")
        img = np.array(img)
        features.append(img)
    features = np.array(features)
    features = features.reshape(len(features), 100, 100,1)
    return features

test_features = extract_features(test['image'])
#print(train_features)
x_test = test_features/255.0
print(x_test)

100%|██████████| 1/1 [00:00<00:00, 142.79it/s]

[[[[0.76862745]
   [0.76862745]
   [0.76862745]
   ...
   [0.80784314]
   [0.80784314]
   [0.80784314]]

  [[0.76862745]
   [0.76862745]
   [0.76862745]
   ...
   [0.80784314]
   [0.80784314]
   [0.80784314]]

  [[0.76862745]
   [0.76862745]
   [0.76862745]
   ...
   [0.80784314]
   [0.80784314]
   [0.80784314]]

  ...

  [[0.68627451]
   [0.78431373]
   [0.76470588]
   ...
   [0.86666667]
   [0.87843137]
   [0.85098039]]

  [[0.74901961]
   [0.80784314]
   [0.75294118]
   ...
   [0.83529412]
   [0.80784314]
   [0.76862745]]

  [[0.75294118]
   [0.84705882]
   [0.81568627]
   ...
   [0.85098039]
   [0.80392157]
   [0.77254902]]]]


In [13]:
## convert label to integer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(test['label'])

LabelEncoder()

In [14]:
correct = 0
count = 0

In [15]:
import random
import matplotlib.pyplot as plt

#image_index = random.randint(0, len(test)-1)
#print("Original Output:", test['label'][image_index])
#pred = model.predict(x_test[image_index].reshape(1, 200, 200, 1))
#prediction_label = le.inverse_transform([pred.argmax()])[0]
#print("Predicted Output:", prediction_label)

# plt.imshow(x_test[image_index].reshape(200, 200), cmap='gray');

# if test['label'][image_index]==prediction_label:
    #correct += 1

#count +=1
#print(f'Accuracy: {correct/count}')

def test_all():
    correct = 0 
    count = 0
    d = dict()

    
    for index in range(len(x_test)):
            original_label = test['label'][index]
            pred = model.predict(x_test[index].reshape(1, 100, 100, 1))
            prediction_label = le.inverse_transform([pred.argmax()])[0]
            
            if original_label==prediction_label:
                correct += 1
            else:
                if original_label in d:
                    d[test['label'][index]] += 1
                else:
                    d[test['label'][index]] = 1
            
            count +=1

            
            print(f"Original : Predicted, {test['label'][index]} : {prediction_label}")
            
    print(d)
    print(f'Overall Accuracy: {correct/count}')        

test_all()

1/1 [==============================] - 18s 18s/step
Original : Predicted, happy : happy
{}
Overall Accuracy: 1.0
